#!/usr/bin/env bash

source .env

clear
echo -ne "
------------------------------------------------------------------------------------------
                                       Dots setup
------------------------------------------------------------------------------------------

                               Press any key to continue...
"
read

echo -ne "
------------------------------------------------------------------------------------------
                                   GRUB configuration
------------------------------------------------------------------------------------------
"
sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
sudo sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
sudo sed -i 's/^#GRUB_DISABLE_SUBMENU=y/GRUB_DISABLE_SUBMENU=y/' /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

echo -ne "
------------------------------------------------------------------------------------------
                                  Installing packages
------------------------------------------------------------------------------------------
"
if [[ ! -f "packages" ]]; then
  echo "Error: packages file not found."
  exit 1
fi
while read line
do
  if [[ $line == "" ]] || [[ $line == \#* ]]; then
    continue
  fi
  sudo pacman -Sy --noconfirm --needed "$line"
done < packages

echo -ne "
------------------------------------------------------------------------------------------
                                     Switch shell
------------------------------------------------------------------------------------------
"
sudo chsh -s ${SHELL} root
sudo chsh -s ${SHELL} ${USERNAME}

echo -ne "
------------------------------------------------------------------------------------------
                              Changing Default Console Font
------------------------------------------------------------------------------------------
"
sudo echo -ne 'KEYMAP="us"
FONT="ter-132b"
' > /etc/vconsole.conf

echo -ne "
------------------------------------------------------------------------------------------
                                Add no password sudo rights
------------------------------------------------------------------------------------------
"
sudo sed -ni "/^root/{a\
  ${USERNAME} ALL=(ALL:ALL) NOPASSWD: ALL
p}" /etc/sudoers

echo -ne "
------------------------------------------------------------------------------------------
                                   Github Configuration      
------------------------------------------------------------------------------------------
"
cd ${HOME}
echo -ne "https://nemo256:${TOKEN}@github.com" > ${HOME}/.git-credentials
git config --global credential.helper store

