#!/usr/bin/env bash

source .env

clear
echo -ne "
------------------------------------------------------------------------------------------
                                       Dots setup
------------------------------------------------------------------------------------------

                               Press any key to continue...
"
read

echo -ne "
------------------------------------------------------------------------------------------
                                   GRUB configuration
------------------------------------------------------------------------------------------
"
sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
sudo sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
sudo sed -i 's/^#GRUB_DISABLE_SUBMENU=y/GRUB_DISABLE_SUBMENU=y/' /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

echo -ne "
------------------------------------------------------------------------------------------
                                  Installing packages
------------------------------------------------------------------------------------------
"
if [[ ! -f "packages" ]]; then
  echo "Error: packages file not found."
  exit 1
fi
while read line
do
  if [[ $line == "" ]] || [[ $line == \#* ]]; then
    continue
  fi
  sudo pacman -Sy --noconfirm --needed "$line"
done < packages

echo -ne "
------------------------------------------------------------------------------------------
                                     Switch shell
------------------------------------------------------------------------------------------
"
sudo chsh -s ${SHELL} root
sudo chsh -s ${SHELL} ${USERNAME}

echo -ne "
------------------------------------------------------------------------------------------
                              Changing Default Console Font
------------------------------------------------------------------------------------------
"
sudo echo -ne 'KEYMAP="us"
FONT="ter-132b"
' > /etc/vconsole.conf

echo -ne "
------------------------------------------------------------------------------------------
                                Add no password sudo rights
------------------------------------------------------------------------------------------
"
sudo sed -ni "/^root/{a\
  ${USERNAME} ALL=(ALL:ALL) NOPASSWD: ALL
p}" /etc/sudoers

echo -ne "
------------------------------------------------------------------------------------------
                                   Github Configuration      
------------------------------------------------------------------------------------------
"
cd ${HOME}
echo -ne "https://nemo256:${TOKEN}@github.com" > ${HOME}/.git-credentials
git config --global credential.helper store

echo -ne "
------------------------------------------------------------------------------------------
                                  Restoring from github
------------------------------------------------------------------------------------------
"
[[ ! -d Documents ]] && git clone https://github.com/nemo256/Documents
[[ ! -d Pictures ]] && git clone https://github.com/nemo256/Pictures
[[ ! -d Music ]] && git clone https://github.com/nemo256/Music
[[ ! -d Templates ]] && git clone https://github.com/nemo256/Templates
[[ ! -d .build ]] && mkdir .build && cd .build
[[ ! -d dwm ]] && git clone https://github.com/nemo256/dwm
[[ ! -d st ]] && git clone https://github.com/nemo256/st
[[ ! -d dmenu ]] && git clone https://github.com/nemo256/dmenu
[[ ! -d slock ]] && git clone https://github.com/nemo256/slock
[[ ! -d slstatus ]] && git clone https://github.com/nemo256/slstatus
[[ ! -d fetchy ]] && git clone https://github.com/nemo256/fetchy
[[ ! -d ani-cli ]] && git clone https://github.com/pystardust/ani-cli
[[ ! -d tty-clock ]] && git clone https://github.com/xorg62/tty-clock
[[ ! -d grabc ]] && git clone https://github.com/muquit/grabc
[[ ! -d tremc ]] && git clone https://github.com/tremc/tremc
cd dwm && sudo make clean install
cd ../st && sudo make clean install
cd ../dmenu && sudo make clean install
cd ../slock && sudo make clean install
cd ../slstatus && sudo make clean install
cd ../fetchy && sudo make clean install
cd ../ani-cli && sudo chmod +x ani-cli && sudo cp -fvr ani-cli /usr/local/bin/ani-cli
cd ../tty-clock && make && sudo make install
cd ../grabc && make && sudo make install
cd ../tremc && sudo make install
yarn global add @aweary/alder
yarn global add weather-cli

echo -ne "
------------------------------------------------------------------------------------------
                                 Restoring Home Directory
------------------------------------------------------------------------------------------
"
cd ${HOME} && mkdir Videos Work

echo -ne "
------------------------------------------------------------------------------------------
                                Stowing Configuration Files
------------------------------------------------------------------------------------------
"
rm -fvr ${HOME}/.bash*
rm -fvr ${HOME}/.gitconfig
rm -fvr ${HOME}/.config/*

cd ${HOME}/dots

stow abook
stow bin
stow bash
stow dunst
stow git
stow gtk-2.0
stow gtk-3.0
stow htop
stow irssi
stow mbsync
stow mimeapps
stow mpd
stow mpv
stow mutt
stow ncmpcpp
stow neofetch
stow newsboat
stow notmuch
stow nvim
stow picom
stow ranger
stow sxiv
stow transmission-daemon
stow tremc
stow weather-cli-nodejs
stow xinit
stow yarn
stow zathura

